name: Dependency-Track Integration (Java)

on:
  push:
    branches: [ master ]

jobs:
  sbom-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'  # Change to 11 or 21 as per your project

    - name: Build Java App
      run: mvn clean package --batch-mode

    - name: Generate SBOM using Syft
      uses: anchore/sbom-action@v0.15.6
      with:
        format: cyclonedx
        output-file: sbom.xml
        path: target/
        upload-artifact: false

    - name: Upload SBOM to Dependency-Track
      env:
        API_KEY: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
        DT_URL: ${{ secrets.DEPENDENCY_TRACK_API_URL }}
        PROJECT_UUID: ${{ secrets.DEPENDENCY_TRACK_PROJECT_UUID }}
      run: |
        echo "Uploading SBOM to Dependency-Track"
        curl -X "POST" "$DT_URL/api/v1/bom" \
             -H "X-Api-Key: $API_KEY" \
             -H "Content-Type: multipart/form-data" \
             -F "project=$PROJECT_UUID" \
             -F "bom=@sbom.xml"
